### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by diivious** [CiscoSteve/DataMiner#3]
Traceback (most recent call last):
  File "D:\Projects\DataMiner\Data Miner v1.0.0.16.py", line 6056, in <module>
    pxc_software_group_suggestions_bug_list()  # requires CSV data from pxc_software_group_suggestions
  File "D:\Projects\DataMiner\Data Miner v1.0.0.16.py", line 4068, in pxc_software_group_suggestions_bug_list
    reply = json.loads(response.text)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by PythonAPICoder** [comment]
Are you executing all the functions in the script or did you limit the focus of what to grab? 
please explain how your executing the script in as much detail as you can.
I ask because the comments in the script explain which functions rely on other functions... the message in your port says:
pxc_software_group_suggestions_bug_list() # requires CSV data from pxc_software_group_suggestions
so if you attempting to run just the pxc_software_group_suggestions_bug_list then you'll also need to make sure the function required are also executed.

**Comment by diivious** [comment]
Ran the script with no options - so all the capabilities.  Note that I changed the debug level to "2" and the issue no longer shows up.  You can close this ticket and it it shows up again, I will collect logs and let you know
